import os

# Import make_page from v2 without running its loop
_v2_src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "generate_steden_v2.py"), encoding="utf-8").read()
_cut = _v2_src.find("\noutput_dir =")
_ns = {}
exec(compile(_v2_src[:_cut], "generate_steden_v2.py", "exec"), _ns)
_make_page = _ns["make_page"]

# ── 50 nieuwe steden binnen ~100 km van Almelo ──────────────────────────────
steden_nieuw = [
    {
        "slug": "borne",
        "stad": "Borne",
        "provincie": "Overijssel",
        "wijken": "Hertme, Zenderen, Bornerbroek, Westermaat-Oost en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande gezinswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "grotendeels gebouwd in de periode 1950-1985 als industrieplaats in Twente",
        "lokaal": "Borne ligt op slechts 10 km van Almelo en heeft een typische Twentse woningvoorraad. Rijtjeswoningen en vrijstaande woningen uit de jaren 60 en 70 zijn energetisch sterk verouderd. Met ruim 23.000 inwoners is het een compacte gemeente waar kozijnenvervanging een directe en merkbare investering is.",
        "klimaat": "Twente heeft een continentaler klimaat dan de kustprovincies, met koude winters en warmere zomers. Goede isolatie via HR++ kozijnen is hier extra relevant voor zowel comfort als energiebesparing het hele jaar door.",
        "label": "Oudere woningen in Borne hebben gemiddeld energielabel D of E.",
        "markt": "Borne heeft een actieve woningmarkt in het hart van Twente. Verduurzaming via kozijnen verhoogt energielabel en verkoopwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle landelijke subsidies beschikbaar voor woningeigenaren in Borne. Wij begeleiden de aanvraag stap voor stap vanuit onze vestiging in Almelo.",
    },
    {
        "slug": "oldenzaal",
        "stad": "Oldenzaal",
        "provincie": "Overijssel",
        "wijken": "De Thij, Berghuizen, Vossenbelt, Beuningen en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, arbeiders-gezinswoningen en vrijstaande woningen",
        "bouwjaar": "met veel woningen gebouwd in de groeijaren 1950-1980 door de textiel- en rubber-industrie",
        "lokaal": "Oldenzaal is een oude Hanzestad op de grens met Duitsland. Wijken als De Thij en Berghuizen tellen veel naoorlogse rijtjeswoningen met verouderde kozijnen. De stad heeft een karakteristieke mix van historische panden en naoorlogse woningbouw die sterk baat heeft bij kozijnenvernieuwing.",
        "klimaat": "Op de Twentse stuwwal heeft Oldenzaal een iets continentaler klimaat. Koudere winters en hogere windbelasting maken HR++ kozijnen extra rendabel.",
        "label": "Naoorlogse woningen in Oldenzaal hebben gemiddeld energielabel D of slechter.",
        "markt": "Oldenzaal heeft een solide woningmarkt op de grens van Twente en Duitsland. Verduurzaming verhoogt de waarde en verkoopbaarheid aantoonbaar.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn volledig beschikbaar voor eigenaar-bewoners in Oldenzaal. Wij begeleiden de subsidieaanvraag volledig.",
    },
    {
        "slug": "rijssen",
        "stad": "Rijssen",
        "provincie": "Overijssel",
        "wijken": "Enterbroek, Elsenerbroek, Rijssen-Noord, Holten en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande woningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met veel gezinswoningen gebouwd in de naoorlogse groeiperiode 1955-1985",
        "lokaal": "Rijssen-Holten is een groeigemeente met een sterk karakter op de grens van Twente en Salland. De woningvoorraad bestaat overwegend uit gezinswoningen op ruime kavels. Na 40 tot 70 jaar zijn de kozijnen in veel van deze woningen energetisch verouderd en toe aan vervanging.",
        "klimaat": "De overgang van Twente naar het Sallandse landschap geeft Rijssen een relatief continentaal klimaat. Goede isolatie is hier zomer en winter voelbaar op de energierekening.",
        "label": "Oudere woningen in Rijssen hebben gemiddeld energielabel C, D of E.",
        "markt": "Rijssen heeft een actieve woningmarkt. Verduurzaming is een bewezen waardestijger in deze regio.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar. Wij begeleiden vanuit Almelo de aanvraag voor Rijssense woningeigenaren volledig.",
    },
    {
        "slug": "haaksbergen",
        "stad": "Haaksbergen",
        "provincie": "Overijssel",
        "wijken": "Buurse, Sint Isidorushoeve, Haaksbergen-Noord, Haaksbergen-Zuid en het Centrum",
        "woningtype": "vrijstaande woningen, twee-onder-een-kapwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met veel woningbouw uit de periode 1955-1985 in een groene plattelandsomgeving",
        "lokaal": "Haaksbergen is een groene grensgemeente met Duitsland en heeft een karakteristieke Twentse woningvoorraad. Vrijstaande woningen op ruime kavels vormen een groot deel van de voorraad. Kozijnen uit de jaren 70 en 80 zijn hier energetisch de zwakste schakel.",
        "klimaat": "Twente heeft een continentaler klimaat dan de kust. Wanden en glas van woningen in Haaksbergen zijn extra belast door koude winters en warme zomers, een goede reden voor HR++ isolatieglas.",
        "label": "Woningen uit de jaren 70 en 80 in Haaksbergen hebben gemiddeld energielabel C of D.",
        "markt": "Haaksbergen heeft een rustige, solide woningmarkt. Verduurzaming verhoogt de woningwaarde en maakt je woning aantrekkelijker.",
        "subsidie_lokaal": "ISDE-subsidie en het Nationaal Warmtefonds zijn beschikbaar voor alle woningeigenaren in Haaksbergen.",
    },
    {
        "slug": "goor",
        "stad": "Goor",
        "provincie": "Overijssel",
        "wijken": "Diepenheim, Markelo, Hengevelde, Goor-West en het Centrum",
        "woningtype": "Twentse vrijstaande woningen, rijtjeswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met een mix van vooroorlogse bebouwing en naoorlogse uitbreidingen in het Hof van Twente",
        "lokaal": "Goor is het centrum van de gemeente Hof van Twente, een groene gemeenten met veel vrijstaande woningen en buitengebied. De woningvoorraad is gevarieerd, van historische dorpspanden tot naoorlogse rijtjeswoningen. In beide categorieën zijn kozijnen een logische eerste stap in verduurzaming.",
        "klimaat": "Het heuvelachtige Twentse landschap rond Goor heeft een relatief droog en continentaal klimaat. Goede isolatie via HR++ kozijnen is direct merkbaar op stookkosten en comfort.",
        "label": "Oudere woningen in Goor en de Hof van Twente hebben gemiddeld energielabel C of D.",
        "markt": "Goor en de Hof van Twente zijn populair bij gezinnen die ruimte zoeken. Verduurzaming verhoogt de woningwaarde in deze gewilde regio.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in de gemeente Hof van Twente.",
    },
    {
        "slug": "wierden",
        "stad": "Wierden",
        "provincie": "Overijssel",
        "wijken": "Enter, Hoge Hexel, Notter, Wierden-Noord en het Centrum",
        "woningtype": "vrijstaande agrarische woningen, rijtjeswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met een mix van kleinere kernen en een moderne woningmarkt op de grens van Twente",
        "lokaal": "Wierden is een compacte gemeente tussen Almelo en Rijssen met meerdere kleine kernen. De woningvoorraad bestaat grotendeels uit gezinswoningen op ruime kavels. Kozijnen uit de jaren 70 tot 90 zijn in veel woningen toe aan vervanging na 40 jaar.",
        "klimaat": "Centraal in Twente heeft Wierden een typisch continentaal binnenlands klimaat. HR++ isolatieglas maakt in deze regio een significant verschil op de jaarlijkse stookkosten.",
        "label": "Woningen in Wierden hebben gemiddeld energielabel C of D.",
        "markt": "Wierden heeft een actieve lokale woningmarkt. Verduurzaming via kozijnen is hier een bewuste investering met korte terugverdientijd.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in de gemeente Wierden.",
    },
    {
        "slug": "hellendoorn",
        "stad": "Hellendoorn",
        "provincie": "Overijssel",
        "wijken": "Nijverdal, Hellendoorn-Dorp, Daarlerveen, Den Ham en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande woningen en textielarbeiders-woningen",
        "bouwjaar": "met veel woningbouw uit de Twentse industrieperiode 1945-1980 rondom Nijverdal",
        "lokaal": "Hellendoorn is een uitgestrekte gemeente aan de rand van Twente en het Sallandse landschap. Nijverdal, de grootste kern, heeft veel naoorlogse woningbouw van textielarbeiders. In wijken zoals Nijverdal-Noord en Hellendoorn-Dorp zijn de kozijnen energetisch een knelpunt.",
        "klimaat": "Op de grens van Twente en Salland is het klimaat continentaal met koude winters. HR++ kozijnen zijn hier extra lonend dankzij het hogere stookverbruik.",
        "label": "Naoorlogse woningen in Hellendoorn hebben gemiddeld energielabel D of E.",
        "markt": "Hellendoorn heeft een mooie woningmarkt in een groene omgeving. Verduurzaming verhoogt de aantrekkelijkheid en waarde van je woning aantoonbaar.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle landelijke subsidies beschikbaar voor woningeigenaren in Hellendoorn.",
    },
    {
        "slug": "vriezenveen",
        "stad": "Vriezenveen",
        "provincie": "Overijssel",
        "wijken": "Westerhaar, Vroomshoop, Den Hulst, Bruinehaar en het Centrum",
        "woningtype": "vrijstaande veenkoloniale woningen, rijtjeswoningen en agrarische woningen",
        "bouwjaar": "met een karakteristieke veenkoloniale bebouwingsstructuur en naoorlogse woningbouw",
        "lokaal": "Vriezenveen maakt deel uit van de gemeente Twenterand en heeft een bijzondere veenkoloniale geschiedenis. De langgerekte bebouwingsstructuur en vrijstaande woningen op ruime kavels zijn kenmerkend. Kozijnen uit de jaren 70 en 80 zijn in veel woningen toe aan vervanging.",
        "klimaat": "Het open veengebied van Twenterand is windgevoelig. Goed geïsoleerde kunststof kozijnen met HR++ glas zijn hier extra waardevol voor tochtwering en warmtebehoud.",
        "label": "Woningen in Vriezenveen hebben gemiddeld energielabel C of D.",
        "markt": "Twenterand heeft een betaalbare woningmarkt. Verduurzaming is een directe investering die zich snel terugverdient.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn volledig beschikbaar voor eigenaar-bewoners in de gemeente Twenterand.",
    },
    {
        "slug": "hardenberg",
        "stad": "Hardenberg",
        "provincie": "Overijssel",
        "wijken": "Dedemsvaart, Slagharen, Gramsbergen, Balkbrug en het Centrum",
        "woningtype": "vrijstaande dorpswoningen, naoorlogse rijtjeswoningen en agrarische woningen",
        "bouwjaar": "met naoorlogse groei en veel woningbouw uit de periode 1955-1985 in de kernen",
        "lokaal": "Hardenberg is een uitgestrekte gemeente in het noorden van Overijssel met meerdere grote kernen waaronder Dedemsvaart. De woningvoorraad bestaat grotendeels uit grondgebonden woningen. Kozijnen uit de jaren 60 tot 80 zijn hier energetisch verouderd en aan vervanging toe.",
        "klimaat": "Noord-Overijssel heeft een continentaal klimaat met koude winters. Het open landschap zorgt voor hogere windbelasting op woningen, waardoor goede afdichting en HR++ glas extra waardevol zijn.",
        "label": "Oudere woningen in Hardenberg en Dedemsvaart hebben gemiddeld energielabel D of E.",
        "markt": "Hardenberg heeft een betaalbare woningmarkt. Verduurzaming verhoogt het energielabel en de verkoopwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Hardenberg.",
    },
    {
        "slug": "dalfsen",
        "stad": "Dalfsen",
        "provincie": "Overijssel",
        "wijken": "Lemelerveld, Nieuwleusen, Hoonhorst, Dalfsen-Dorp en het Centrum",
        "woningtype": "vrijstaande Sallandse woningen, twee-onder-een-kapwoningen en dorpsrijtjeswoningen",
        "bouwjaar": "met een typische Sallandse bebouwingsstructuur van vrijstaande woningen en kleine kernen",
        "lokaal": "Dalfsen is een groene gemeente in het hart van Salland, tussen Zwolle en Almelo in. De gemeente staat bekend om de hoge woningkwaliteit en groene omgeving. Toch zijn kozijnen uit de jaren 70 tot 90 ook hier aan vervanging toe, met directe energiebesparing als resultaat.",
        "klimaat": "Het Sallandse rivierengebied heeft een gematigd klimaat. Goede isolatie via HR++ kozijnen is het hele jaar door voelbaar op de energierekening.",
        "label": "Oudere Sallandse woningen in Dalfsen hebben gemiddeld energielabel C of D.",
        "markt": "Dalfsen is populair bij gezinnen die rust en ruimte zoeken. De woningmarkt is actief en verduurzaming vergroot de aantrekkelijkheid direct.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn volledig beschikbaar voor eigenaar-bewoners in Dalfsen.",
    },
    {
        "slug": "raalte",
        "stad": "Raalte",
        "provincie": "Overijssel",
        "wijken": "Heino, Marienheem, Luttenberg, Nieuw-Heeten en het Centrum",
        "woningtype": "vrijstaande Sallandse woningen, rijtjeswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met naoorlogse groei en een gevarieerde woningvoorraad in meerdere kleine kernen",
        "lokaal": "Raalte is het centrum van Salland, tussen Zwolle en Almelo. De gemeente telt meerdere dorpskernen met een gevarieerde woningvoorraad. Vrijstaande woningen en twee-onder-een-kapwoningen uit de jaren 60 tot 85 hebben hier vaak verouderde kozijnen die energetisch de zwakste schakel zijn.",
        "klimaat": "In het hart van Salland heeft Raalte een gematigd klimaat met continentale invloeden. HR++ kozijnen zorgen voor merkbare energiebesparing in de wintermaanden.",
        "label": "Oudere woningen in Raalte hebben gemiddeld energielabel C of D.",
        "markt": "Raalte en de Sallandse regio zijn geliefd. Verduurzaming via kozijnen verhoogt de waarde en verkoopbaarheid in deze actieve markt.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies en financieringsmogelijkheden beschikbaar voor eigenaar-bewoners in Raalte.",
    },
    {
        "slug": "kampen",
        "stad": "Kampen",
        "provincie": "Overijssel",
        "wijken": "Brunnepe, Onderdijks, IJsselmuiden, Grafhorst en het Centrum",
        "woningtype": "historische Hanzepanden, naoorlogse rijtjeswoningen en polderwoningen",
        "bouwjaar": "met een rijke historische binnenstad en uitgestrekte naoorlogse woningbouw",
        "lokaal": "Kampen is een historische Hanzestad aan de IJssel met een van de best bewaarde middeleeuwse binnensteden van Nederland. Buiten het centrum hebben wijken als Brunnepe en IJsselmuiden naoorlogse woningbouw die energetisch sterk te verbeteren is via nieuwe kozijnen.",
        "klimaat": "Aan de IJsseldelta heeft Kampen een vochtig, winderig klimaat. Kunststof kozijnen zijn roestvrij en vochtbestendig, ideaal voor deze delta-omgeving.",
        "label": "Historische Kampense panden hebben gemiddeld energielabel E of F. Naoorlogse woningen scoren D.",
        "markt": "Kampen is geliefd om zijn historische karakter en heeft een actieve woningmarkt. Verduurzaming verhoogt energielabel en woningwaarde direct.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar. Bij historische panden adviseren wij gratis over de mogelijkheden binnen de bouwkundige eisen.",
    },
    {
        "slug": "steenwijk",
        "stad": "Steenwijk",
        "provincie": "Overijssel",
        "wijken": "Steenwijkerwold, Tuk, Ossenzijl, Sint Jansklooster en het Centrum",
        "woningtype": "vrijstaande woningen, twee-onder-een-kapwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met naoorlogse groei als regionaal centrum in Noordwest-Overijssel",
        "lokaal": "Steenwijk is het regionale centrum van Steenwijkerland in Noordwest-Overijssel, dicht bij het Nationaal Park Weerribben-Wieden. De woningvoorraad bestaat uit een mix van vrijstaande woningen en naoorlogse rijtjeswoningen. Kozijnen uit de jaren 70 en 80 zijn hier aan vervanging toe.",
        "klimaat": "Noordwest-Overijssel is windgevoelig en vochtig. Goede isolatiekozijnen zijn extra waardevol in dit open laagveengebied.",
        "label": "Oudere woningen in Steenwijk hebben gemiddeld energielabel C of D.",
        "markt": "Steenwijk heeft een rustige, solide woningmarkt als poort tot het Nationaal Park. Verduurzaming is een slimme investering.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in Steenwijkerland.",
    },
    {
        "slug": "losser",
        "stad": "Losser",
        "provincie": "Overijssel",
        "wijken": "De Lutte, Overdinkel, Beuningen, Glane en het Centrum",
        "woningtype": "vrijstaande woningen, twee-onder-een-kapwoningen en grensstreek-woningbouw",
        "bouwjaar": "met een karakteristieke bebouwing op de grens van Twente en Duitsland",
        "lokaal": "Losser is een grensstreekgemeente tussen Enschede en de Duitse grens met idyllische dorpen als De Lutte. De woningvoorraad bestaat grotendeels uit vrijstaande woningen en twee-onder-een-kapwoningen op ruime kavels. Kozijnen uit de jaren 70 en 80 zijn hier aan energetische verversing toe.",
        "klimaat": "Op de Twentse stuwwal richting de grens heeft Losser een iets windrijker klimaat. HR++ glas is hier extra relevant voor het verminderen van warmteverlies.",
        "label": "Woningen in Losser hebben gemiddeld energielabel C of D.",
        "markt": "Losser is populair om zijn rust en grensligging. De woningmarkt is actief en verduurzaming vergroot de aantrekkelijkheid.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor eigenaar-bewoners in Losser.",
    },
    {
        "slug": "tubbergen",
        "stad": "Tubbergen",
        "provincie": "Overijssel",
        "wijken": "Albergen, Fleringen, Manderveen, Reutum en het Centrum",
        "woningtype": "vrijstaande boerderijen, twee-onder-een-kapwoningen en dorpsrijtjeswoningen",
        "bouwjaar": "met een typische Twentse plattelandsbebouwing van vrijstaande woningen op ruime erven",
        "lokaal": "Tubbergen is een landelijke gemeente in het hart van Twente met een authentieke plattelandsidentiteit. De woningvoorraad bestaat grotendeels uit vrijstaande woningen en boerderijen. Kozijnen uit de jaren 60 tot 90 zijn hier energetisch verouderd, met grote potentiële besparing bij vervanging.",
        "klimaat": "Het Twentse binnenland heeft een continentaler klimaat met koude winters. Op vrijstaande woningen in het buitengebied zijn kozijnen extra relevant voor tochtwering.",
        "label": "Oudere woningen in Tubbergen hebben gemiddeld energielabel C, D of lager.",
        "markt": "Tubbergen is geliefd om zijn rust en ruimte. Verduurzaming via kozijnen is hier een bewuste langetermijninvestering.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor alle eigenaar-bewoners in Tubbergen.",
    },
    {
        "slug": "denekamp",
        "stad": "Denekamp",
        "provincie": "Overijssel",
        "wijken": "Lattrop, Tilligte, Oud Ootmarsum, Rossum en het Centrum",
        "woningtype": "vrijstaande Twentse woningen, twee-onder-een-kapwoningen en boerderijwoningen",
        "bouwjaar": "met een authentieke Twentse plattelandsbebouwing op de grens met Duitsland",
        "lokaal": "Denekamp maakt deel uit van de gemeente Dinkelland, het meest oostelijke punt van Overijssel, grenzend aan Duitsland. De woningvoorraad bestaat grotendeels uit vrijstaande woningen in groene omgevingen. Na 40 tot 60 jaar zijn de kozijnen in veel woningen energetisch aan vervanging toe.",
        "klimaat": "Oost-Twente op de grens met Duitsland heeft een relatief continentaal klimaat met koude winters. Goede isolatie via HR++ kozijnen is hier extra lonend.",
        "label": "Woningen in Denekamp hebben gemiddeld energielabel C of D.",
        "markt": "Dinkelland heeft een rustige, authentieke woningmarkt. Verduurzaming is hier een slimme investering voor de lange termijn.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Dinkelland.",
    },
    {
        "slug": "olst",
        "stad": "Olst",
        "provincie": "Overijssel",
        "wijken": "Wijhe, Welsum, Boskamp, Olst-Dorp en het Centrum",
        "woningtype": "vrijstaande IJsselbuurt-woningen, rijtjeswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met een gevarieerde woningvoorraad langs de IJssel in de gemeente Olst-Wijhe",
        "lokaal": "Olst-Wijhe is een groene gemeente langs de IJssel tussen Deventer en Zwolle. De woonkernen Olst en Wijhe hebben een karakteristieke Sallandse woningvoorraad. Vrijstaande woningen en twee-onder-een-kapwoningen uit de jaren 60 tot 85 hebben hier kozijnen die aan vervanging toe zijn.",
        "klimaat": "Langs de IJssel heeft Olst een gematigd klimaat met koele winters. HR++ kozijnen zijn hier een directe investering in wooncomfort en lagere stookkosten.",
        "label": "Oudere woningen in Olst-Wijhe hebben gemiddeld energielabel C of D.",
        "markt": "Olst-Wijhe is geliefd om rust, ruimte en de IJsselligging. Verduurzaming verhoogt de woningwaarde in deze gewilde regio.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in Olst-Wijhe.",
    },
    {
        "slug": "ommen",
        "stad": "Ommen",
        "provincie": "Overijssel",
        "wijken": "Vilsteren, Arriën, Stegeren, Beerze en het Centrum",
        "woningtype": "vrijstaande bungalows, toeristische woonwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met een typische toeristische woonstructuur in een bosrijke Vecht-omgeving",
        "lokaal": "Ommen ligt aan de Vecht in een van de mooiste bosrijke gebieden van Overijssel. De gemeente trekt mensen die ruimte en natuur zoeken. De woningvoorraad bestaat grotendeels uit vrijstaande woningen en bungalows. Kozijnen uit de jaren 70 en 80 zijn hier aan energetische vernieuwing toe.",
        "klimaat": "In het bosrijke Vechtgebied is het klimaat relatief mild. Toch maken de koude winters en hoge glasoppervlakte van vrijstaande woningen HR++ kozijnen hier extra lonend.",
        "label": "Woningen in Ommen hebben gemiddeld energielabel C of D.",
        "markt": "Ommen is populair als woon- en recreatiegemeente. Verduurzaming is hier een investering die de woning aantrekkelijker maakt voor een groeiende groep kopers.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor eigenaar-bewoners in Ommen.",
    },
    {
        "slug": "staphorst",
        "stad": "Staphorst",
        "provincie": "Overijssel",
        "wijken": "Rouveen, IJhorst, Nieuwleusen-Noord, Staphorst-Streek en het Centrum",
        "woningtype": "vrijstaande streekwoningen, boerderijwoningen en naoorlogse gezinswoningen",
        "bouwjaar": "met een kenmerkende lintbebouwing van vrijstaande woningen op smalle lange erven",
        "lokaal": "Staphorst is een gemeente met een bijzondere cultuur en karakteristieke lintbebouwing. De unieke streekwoningen op lange erven vormen een groot deel van de woningvoorraad. Kozijnen in deze woningen zijn energetisch vaak verouderd, en vervanging door moderne HR++ kozijnen levert hier directe besparing op.",
        "klimaat": "Het open Overijsselse veenlandschap bij Staphorst is windgevoelig. Goed geïsoleerde kozijnen verminderen tocht en warmteverlies significant.",
        "label": "Oudere woningen in Staphorst hebben gemiddeld energielabel C of D.",
        "markt": "Staphorst heeft een hechte, actieve woningmarkt. Verduurzaming is hier een bewuste langetermijninvestering.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in Staphorst.",
    },
    {
        "slug": "doetinchem",
        "stad": "Doetinchem",
        "provincie": "Gelderland",
        "wijken": "De Wijnbergen, Dichteren, Overstegen, Gaanderen en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande woningen en portieketagewoningen",
        "bouwjaar": "met veel wederopbouwwoningen na de Tweede Wereldoorlog en naoorlogse uitbreidingen",
        "lokaal": "Doetinchem is de grootste stad van de Achterhoek en werd zwaar getroffen in de Tweede Wereldoorlog. De woningvoorraad bestaat grotendeels uit naoorlogse bouw. Wijken als De Wijnbergen en Overstegen tellen veel woningen uit de jaren 50 en 60 die energetisch sterk te verbeteren zijn.",
        "klimaat": "De Achterhoek heeft een continentaal klimaat, droger en koeler dan de kust. HR++ kozijnen zijn hier extra waardevol voor het verminderen van warmteverlies in de wintermaanden.",
        "label": "Naoorlogse woningen in Doetinchem hebben gemiddeld energielabel D of E.",
        "markt": "Doetinchem heeft een actieve woningmarkt als centrum van de Achterhoek. Verduurzaming verhoogt energielabel en verkoopwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Doetinchem en de Achterhoek.",
    },
    {
        "slug": "zutphen",
        "stad": "Zutphen",
        "provincie": "Gelderland",
        "wijken": "Leesten, De Hoven, Waterkwartier, Warnsveld en het Centrum",
        "woningtype": "historische Hanzepanden, naoorlogse rijtjeswoningen en vrijstaande woningen",
        "bouwjaar": "met een rijke historische kern en uitgestrekte naoorlogse woningbouw",
        "lokaal": "Zutphen is een historische Hanzestad aan de IJssel en Berkel. De gevarieerde woningvoorraad loopt uiteen van historische panden in de binnenstad tot naoorlogse rijtjeswoningen in wijken als Leesten en Waterkwartier. Juist in de naoorlogse bouw zijn kozijnen de zwakste energetische schakel.",
        "klimaat": "Aan de IJssel heeft Zutphen een gematigd, licht continentaal klimaat. Goede isolatie via HR++ kozijnen is het hele jaar door voelbaar in comfort en stookkosten.",
        "label": "Historische Zutphense panden scoren energielabel E of F. Naoorlogse woningen gemiddeld D.",
        "markt": "Zutphen combineert historische charme met een moderne woningmarkt. Verduurzaming vergroot de woningwaarde en verkoopbaarheid.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn volledig beschikbaar. Bij historische panden adviseren wij gratis over de mogelijkheden.",
    },
    {
        "slug": "winterswijk",
        "stad": "Winterswijk",
        "provincie": "Gelderland",
        "wijken": "Miste, Meddo, Corle, Winterswijk-West en het Centrum",
        "woningtype": "vrijstaande Achterhoekse woningen, twee-onder-een-kapwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met naoorlogse groei en een gevarieerde woningvoorraad in de Achterhoekse grensstreek",
        "lokaal": "Winterswijk is de meest oostelijke stad van Gelderland, direct op de grens met Duitsland. De stad heeft een levendig centrum en een gevarieerde woningvoorraad. Zowel de naoorlogse rijtjeswoningen als de vrijstaande woningen in het buitengebied hebben kozijnen die energetisch aan vervanging toe zijn.",
        "klimaat": "De Achterhoek op de grens met Duitsland heeft een continentaler klimaat met koude winters. Goede isolatie via HR++ kozijnen is hier extra lonend.",
        "label": "Oudere woningen in Winterswijk hebben gemiddeld energielabel C of D.",
        "markt": "Winterswijk heeft een authentieke woningmarkt in de Achterhoek. Verduurzaming is hier een slimme investering.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Winterswijk.",
    },
    {
        "slug": "lochem",
        "stad": "Lochem",
        "provincie": "Gelderland",
        "wijken": "Laren, Gorssel, Epse, Barchem en het Centrum",
        "woningtype": "vrijstaande landgoedbebouwing, twee-onder-een-kapwoningen en naoorlogse gezinswoningen",
        "bouwjaar": "met een gevarieerde bebouwingsstructuur in het groene Achterhoekse landschap",
        "lokaal": "Lochem is een groene gemeente in de Achterhoek, bekend om de afwisseling van landgoederen, bossen en heidevelden. De woningvoorraad is gevarieerd, van vrijstaande woningen op ruime kavels tot naoorlogse gezinswoningen in de kern. Kozijnen uit de jaren 70 en 80 zijn hier aan energetische vernieuwing toe.",
        "klimaat": "In het heuvelachtige Achterhoekse landschap is het klimaat gematigd en relatief droog. HR++ kozijnen zijn hier de meest kosteneffectieve stap in verduurzaming.",
        "label": "Oudere woningen in Lochem hebben gemiddeld energielabel C of D.",
        "markt": "Lochem trekt woningzoekers die rust en natuur zoeken. Verduurzaming verhoogt de waarde en aantrekkelijkheid van je woning.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in de gemeente Lochem.",
    },
    {
        "slug": "eibergen",
        "stad": "Eibergen",
        "provincie": "Gelderland",
        "wijken": "Neede, Borculo, Ruurlo, Beltrum en het Centrum",
        "woningtype": "vrijstaande Achterhoekse woningen, rijtjeswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met een naoorlogse groei en kleinschalige kernen in de gemeente Berkelland",
        "lokaal": "Eibergen maakt deel uit van de gemeente Berkelland in de Achterhoek. De gemeente telt meerdere kleine kernen waaronder Neede en Borculo. De woningvoorraad bestaat overwegend uit grondgebonden woningen. Kozijnen uit de jaren 60 tot 85 zijn hier energetisch verouderd.",
        "klimaat": "De Berkelstreek heeft een gematigd continentaal klimaat. Goede isolatie via HR++ kozijnen zorgt voor lagere stookkosten en meer comfort.",
        "label": "Woningen in Eibergen en de gemeente Berkelland hebben gemiddeld energielabel C of D.",
        "markt": "Berkelland heeft een actieve woningmarkt in de groene Achterhoek. Verduurzaming vergroot de woningwaarde en verkoopbaarheid.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Berkelland.",
    },
    {
        "slug": "groenlo",
        "stad": "Groenlo",
        "provincie": "Gelderland",
        "wijken": "Zieuwent, Marienvelde, Vragender, Groenlo-West en het Centrum",
        "woningtype": "vrijstaande Achterhoekse woningen, naoorlogse rijtjeswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met naoorlogse groei als vesting- en marktplaats in de gemeente Oost Gelre",
        "lokaal": "Groenlo is een historische vestingstad in de gemeente Oost Gelre, bekend om zijn Grolsch-bier erfgoed. Naast het historische centrum zijn er uitgestrekte naoorlogse wijken. Woningen uit de jaren 60 tot 80 hebben hier kozijnen die energetisch aan vervanging toe zijn.",
        "klimaat": "Oost Gelre op de grens met Duitsland heeft een continentaler klimaat dan de kust. HR++ kozijnen zijn hier extra lonend vanwege de koude winters.",
        "label": "Oudere woningen in Groenlo en Oost Gelre hebben gemiddeld energielabel C of D.",
        "markt": "Oost Gelre heeft een solide, betaalbare woningmarkt. Verduurzaming is hier een directe waardestijger.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in de gemeente Oost Gelre.",
    },
    {
        "slug": "lichtenvoorde",
        "stad": "Lichtenvoorde",
        "provincie": "Gelderland",
        "wijken": "Zieuwent, Vragender, Harreveld, Lievelde en het Centrum",
        "woningtype": "vrijstaande Achterhoekse woningen, twee-onder-een-kapwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met naoorlogse groei in kleinschalige kernen van de gemeente Oost Gelre",
        "lokaal": "Lichtenvoorde is het andere centrum van de gemeente Oost Gelre. De woningvoorraad bestaat grotendeels uit grondgebonden woningen in kleinschalige kernen. Kozijnen uit de jaren 60 tot 85 zijn hier aan energetische vernieuwing toe.",
        "klimaat": "In de Achterhoek op de grens met Duitsland zijn de winters kouder dan aan de kust. HR++ kozijnen zijn hier extra waardevol.",
        "label": "Woningen in Lichtenvoorde hebben gemiddeld energielabel C of D.",
        "markt": "Lichtenvoorde heeft een rustige, solide woningmarkt. Verduurzaming is een slimme investering voor de lange termijn.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies volledig beschikbaar voor woningeigenaren in Oost Gelre.",
    },
    {
        "slug": "aalten",
        "stad": "Aalten",
        "provincie": "Gelderland",
        "wijken": "Bredevoort, Dinxperlo, De Heurne, Aalten-West en het Centrum",
        "woningtype": "vrijstaande grensstreek-woningen, naoorlogse rijtjeswoningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met naoorlogse groei als grensstreekgemeente op de grens met Duitsland",
        "lokaal": "Aalten is een grensgemeente in de Achterhoek met de bekende grensplaats Dinxperlo. De woningvoorraad is gevarieerd, van de historische vestingkern Bredevoort tot naoorlogse woningbouw. Kozijnen uit de jaren 60 tot 85 zijn hier energetisch verouderd.",
        "klimaat": "Op de grens met Duitsland is het klimaat continentaler. HR++ kozijnen zijn hier een directe investering in lagere stookkosten.",
        "label": "Oudere woningen in Aalten hebben gemiddeld energielabel C of D.",
        "markt": "Aalten heeft een betaalbare woningmarkt in de Achterhoek. Verduurzaming verhoogt de waarde direct.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in de gemeente Aalten.",
    },
    {
        "slug": "doesburg",
        "stad": "Doesburg",
        "provincie": "Gelderland",
        "wijken": "Beinum, Doesburg-West, IJsselkade, Molenveld en het Centrum",
        "woningtype": "historische Hanzepanden, naoorlogse rijtjeswoningen en vrijstaande woningen",
        "bouwjaar": "met een rijke historische kern aan de IJssel en compacte naoorlogse woningbouw",
        "lokaal": "Doesburg is een van de kleinste stadjes van Nederland met een bijzonder goed bewaard historisch centrum. De historische panden in de binnenstad zijn energetisch slecht geïsoleerd, terwijl in de naoorlogse wijken verouderd dubbel glas de zwakke schakel is.",
        "klimaat": "Aan de IJssel in de Achterhoek heeft Doesburg een gematigd continentaal klimaat. Goede isolatie via HR++ kozijnen is het hele jaar door voelbaar.",
        "label": "Historische Doesburgse panden scoren gemiddeld energielabel E of F.",
        "markt": "Doesburg heeft een unieke woningmarkt met historische charme en groeiende populariteit. Verduurzaming verhoogt de waarde en verkoopbaarheid.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar. Bij historische panden adviseren wij gratis.",
    },
    {
        "slug": "zevenaar",
        "stad": "Zevenaar",
        "provincie": "Gelderland",
        "wijken": "Babberich, Oud-Zevenaar, Didam, Angerlo en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande woningen en Vinex-uitbreidingen",
        "bouwjaar": "met naoorlogse groei en recente uitbreidingen als groeigemeente bij Arnhem",
        "lokaal": "Zevenaar is een groeigemeente in de Liemers, nabij Arnhem en de Duitse grens. De woningvoorraad loopt uiteen van naoorlogse rijtjeswoningen tot recente Vinex-nieuwbouw in Didam. Woningen uit de jaren 70 en 80 zijn energetisch aan vervanging toe.",
        "klimaat": "In de Gelderse Liemers heeft Zevenaar een gematigd continentaal klimaat. HR++ kozijnen zijn hier een kosteneffectieve investering in energiebesparing.",
        "label": "Naoorlogse woningen in Zevenaar hebben gemiddeld energielabel C of D.",
        "markt": "Zevenaar is populair door de nabijheid van Arnhem en de snelweg. Verduurzaming vergroot de aantrekkelijkheid en verkoopwaarde direct.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn volledig beschikbaar voor woningeigenaren in Zevenaar.",
    },
    {
        "slug": "wageningen",
        "stad": "Wageningen",
        "provincie": "Gelderland",
        "wijken": "Nude, Tarthorst, De Eng, Benedenstad en het Centrum",
        "woningtype": "universitaire woningen, naoorlogse rijtjeswoningen en vrijstaande woningen",
        "bouwjaar": "met een mix van naoorlogse universiteitsbebouwing en historische panden",
        "lokaal": "Wageningen is de universiteitsstad van Food Valley, bekend om de Wageningen University. De woningvoorraad bestaat uit een mix van universiteits-gebonden bouw en naoorlogse woningen. Wijken als Tarthorst en Nude hebben woningen met verouderde kozijnen die energetisch te verbeteren zijn.",
        "klimaat": "Aan de Rijn en het Gelderse rivierengebied heeft Wageningen een gematigd klimaat. Goede isolatie via HR++ kozijnen is direct merkbaar op het stookverbruik.",
        "label": "Naoorlogse woningen in Wageningen hebben gemiddeld energielabel C of D.",
        "markt": "Wageningen heeft een actieve woningmarkt door de universiteit. Verduurzaming verhoogt de woningwaarde en verhuurbaarheid.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Wageningen.",
    },
    {
        "slug": "barneveld",
        "stad": "Barneveld",
        "provincie": "Gelderland",
        "wijken": "Voorthuizen, Kootwijkerbroek, Stroe, Barneveld-Noord en het Centrum",
        "woningtype": "vrijstaande Veluwse woningen, twee-onder-een-kapwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met naoorlogse groei als groeigemeente op de Veluwe",
        "lokaal": "Barneveld is een groeigemeente op de Veluwe met meerdere kernen. De woningvoorraad bestaat grotendeels uit grondgebonden gezinswoningen. Na 40 tot 60 jaar zijn de kozijnen in veel woningen energetisch aan vervanging toe, met direct merkbare besparing als resultaat.",
        "klimaat": "Op de Veluwe is het klimaat relatief droog en continentaal met koude winters. Goede isolatie is hier direct merkbaar op de stookkosten.",
        "label": "Oudere woningen in Barneveld hebben gemiddeld energielabel C of D.",
        "markt": "Barneveld heeft een sterk groeiende woningmarkt. Verduurzaming is hier een bewuste investering die direct loont.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn volledig beschikbaar voor woningeigenaren in Barneveld.",
    },
    {
        "slug": "nijkerk",
        "stad": "Nijkerk",
        "provincie": "Gelderland",
        "wijken": "Hoevelaken, Nijkerkerveen, Corlaer, Arkervaart en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, Vinex-woningen en twee-onder-een-kapwoningen",
        "bouwjaar": "met sterke groei als forensengemeente bij Amersfoort en Nijmegen",
        "lokaal": "Nijkerk is een groeigemeente op de grens van Gelderland en Utrecht. De woningvoorraad is gevarieerd, van naoorlogse rijtjeswoningen tot recentere Vinex-nieuwbouw. Woningen uit de jaren 70 tot 90 zijn energetisch aan kozijnenvervanging toe.",
        "klimaat": "Centraal in Nederland heeft Nijkerk een continentaal klimaat. HR++ kozijnen zijn hier een kosteneffectieve stap in verduurzaming.",
        "label": "Oudere woningen in Nijkerk hebben gemiddeld energielabel C of D.",
        "markt": "Nijkerk heeft een sterke woningmarkt door de ligging bij Amersfoort. Verduurzaming vergroot de woningwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Nijkerk.",
    },
    {
        "slug": "nunspeet",
        "stad": "Nunspeet",
        "provincie": "Gelderland",
        "wijken": "Elspeet, Hulshorst, Vierhouten, Nunspeet-West en het Centrum",
        "woningtype": "vrijstaande Veluwse woningen, bungalows en twee-onder-een-kapwoningen",
        "bouwjaar": "met een typische Veluwse bebouwingsstructuur van vrijstaande woningen in bosrijke omgeving",
        "lokaal": "Nunspeet is een groene Veluwse gemeente met een grote populariteit bij gezinnen en senioren. De woningvoorraad bestaat grotendeels uit vrijstaande woningen en bungalows. Kozijnen uit de jaren 70 tot 90 zijn energetisch verouderd en bij vervanging direct merkbaar op de stookkosten.",
        "klimaat": "Op de Veluwe is het klimaat relatief droog en koud in de winter. De grote glasoppervlakte van Veluwse bungalows maakt HR++ glas extra lonend.",
        "label": "Bungalows en vrijstaande woningen in Nunspeet hebben door hun glasoppervlak gemiddeld energielabel D.",
        "markt": "Nunspeet heeft een gewilde woningmarkt. Verduurzaming verhoogt de waarde en aantrekkelijkheid van je woning direct.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar. Bij triple glas ontvang je tot 111 euro per m2 subsidie, ideaal voor grote Veluwse raampartijen.",
    },
    {
        "slug": "harderwijk",
        "stad": "Harderwijk",
        "provincie": "Gelderland",
        "wijken": "Drielanden, Tweelingstad, Friesegracht, Stadsdennen en het Centrum",
        "woningtype": "historische Hanzepanden, naoorlogse rijtjeswoningen en Vinex-woningen in Drielanden",
        "bouwjaar": "met historische kern en grote moderne uitbreidingen als groeigemeente",
        "lokaal": "Harderwijk is een historische Hanzestad aan het Veluwemeer met een druk bezochte binnenstad. Naast het historische centrum heeft Harderwijk grote nieuwbouwwijken als Drielanden. In de naoorlogse woningen zijn kozijnen energetisch de zwakste schakel.",
        "klimaat": "Aan het Veluwemeer heeft Harderwijk een mild klimaat. Maar de naoorlogse en vroeg-negentigse woningbouw profiteert sterk van HR++ kozijnen.",
        "label": "Naoorlogse woningen in Harderwijk hebben gemiddeld energielabel C of D.",
        "markt": "Harderwijk heeft een actieve woningmarkt. Verduurzaming verhoogt energielabel en verkoopwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Harderwijk.",
    },
    {
        "slug": "hoogeveen",
        "stad": "Hoogeveen",
        "provincie": "Drenthe",
        "wijken": "Wolfsbos, Erflanden, Krakeel, De Weide en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande woningen en portieketagewoningen",
        "bouwjaar": "met veel woningbouw uit de naoorlogse industrieperiode 1950-1980",
        "lokaal": "Hoogeveen is een groeigemeente in Drenthe die sterk groeide door de industrie. Wijken als Wolfsbos en Erflanden tellen veel naoorlogse woningen die energetisch sterk verouderd zijn. Nieuwe kozijnen maken hier een direct merkbaar verschil in stookkosten en comfort.",
        "klimaat": "Drenthe heeft een continentaal klimaat met koude winters en warme zomers. Het open landschap zorgt voor extra windbelasting op woningen.",
        "label": "Naoorlogse woningen in Hoogeveen hebben gemiddeld energielabel D of E.",
        "markt": "Hoogeveen heeft betaalbare woningen met veel potentieel. Verduurzaming via kozijnen verhoogt energielabel en woningwaarde direct.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn volledig beschikbaar voor eigenaar-bewoners in Hoogeveen.",
    },
    {
        "slug": "meppel",
        "stad": "Meppel",
        "provincie": "Drenthe",
        "wijken": "Oosterboer, Koedijkslanden, Berggierslanden, Nijeveen en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, twee-onder-een-kapwoningen en historische grachtenpanden",
        "bouwjaar": "met historische binnenstad en uitgestrekte naoorlogse woningbouwwijken",
        "lokaal": "Meppel is een compacte Drentse stad met een sfeervolle historische binnenstad. Naast de grachten zijn er uitgestrekte naoorlogse wijken als Koedijkslanden en Berggierslanden met woningen die energetisch aan kozijnenvervanging toe zijn.",
        "klimaat": "Drenthe heeft koude winters en een open landschap. Goed geïsoleerde kozijnen zijn hier een directe investering in lagere stookkosten.",
        "label": "Naoorlogse woningen in Meppel hebben gemiddeld energielabel C of D.",
        "markt": "Meppel is aantrekkelijk door zijn gezellige centrum en bereikbare ligging. Verduurzaming verhoogt de woningwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Meppel.",
    },
    {
        "slug": "coevorden",
        "stad": "Coevorden",
        "provincie": "Drenthe",
        "wijken": "Dalen, Sleen, Zweeloo, De Haar en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande dorpswoningen en historische stadspanden",
        "bouwjaar": "met naoorlogse woningbouw en een karakteristieke vestingstad-kern",
        "lokaal": "Coevorden is een historische vestingstad op de grens van Drenthe en Overijssel. Naast de vesting zijn er naoorlogse wijken en rurale kernen met vrijstaande woningen. In beide categorieeen zijn kozijnen energetisch de zwakste schakel.",
        "klimaat": "De grensstreek van Drenthe en Overijssel heeft een continentaal klimaat met koude winters. HR++ kozijnen zijn hier een directe investering in warmtebehoud.",
        "label": "Oudere woningen in Coevorden hebben gemiddeld energielabel D of E.",
        "markt": "Coevorden heeft een betaalbare woningmarkt. Verduurzaming via kozijnen is hier een slimme investering.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in Coevorden.",
    },
    {
        "slug": "assen",
        "stad": "Assen",
        "provincie": "Drenthe",
        "wijken": "Peelo, Kloosterveen, Pittelo, Marsdijk en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, portieketagewoningen en moderne Vinex-woningen",
        "bouwjaar": "met veel naoorlogse woningbouw en recente uitbreidingen in Kloosterveen",
        "lokaal": "Assen is de hoofdstad van Drenthe en heeft een gevarieerde woningvoorraad. Wijken als Peelo en Marsdijk tellen veel naoorlogse rijtjeswoningen die energetisch sterk te verbeteren zijn, terwijl het nieuwere Kloosterveen ook al toe is aan kozijnenvervanging na 25 jaar.",
        "klimaat": "Drenthe heeft een continentaal klimaat. Als hoofdstad van de koudste provincie van Nederland loont investeren in HR++ isolatieglas hier extra.",
        "label": "Naoorlogse woningen in Assen hebben gemiddeld energielabel D of E.",
        "markt": "Assen heeft een actieve woningmarkt als provinciehoofdstad. Verduurzaming vergroot de woningwaarde en verkoopbaarheid direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Assen en Drenthe.",
    },
    {
        "slug": "stadskanaal",
        "stad": "Stadskanaal",
        "provincie": "Groningen",
        "wijken": "Musselkanaal, Onstwedde, Wildervank-deel, Stadskanaal-Noord en het Centrum",
        "woningtype": "veenkoloniale lintwoningen, naoorlogse rijtjeswoningen en portieketagewoningen",
        "bouwjaar": "met een kenmerkende veenkoloniale bebouwingsstructuur en naoorlogse uitbreidingen",
        "lokaal": "Stadskanaal is een veenkoloniale gemeente in Oost-Groningen met een karakteristieke lintbebouwing langs kanalen. De woningvoorraad bestaat grotendeels uit naoorlogse woningen die energetisch sterk verouderd zijn. Nieuwe kozijnen leveren hier een van de grootste energiebesparingen per euro investering.",
        "klimaat": "Oost-Groningen heeft een continentaal klimaat met koude winters. Het open veenlandschap maakt goede afdichting van kozijnen extra waardevol.",
        "label": "Woningen in Stadskanaal hebben gemiddeld energielabel D, E of slechter.",
        "markt": "Stadskanaal heeft betaalbare woningen met groot verduurzamingspotentieel. Een hoger energielabel verhoogt de waarde merkbaar.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar. Groningers kunnen mogelijk ook profiteren van regionale versterkings- en verduurzamingsprogramma's.",
    },
    {
        "slug": "veendam",
        "stad": "Veendam",
        "provincie": "Groningen",
        "wijken": "Wildervank, Veendam-Zuid, Borgercompagnie, Eexterveensche Kanaal en het Centrum",
        "woningtype": "veenkoloniale woningen, naoorlogse rijtjeswoningen en portieketagewoningen",
        "bouwjaar": "met een typische veenkoloniale bebouwing en naoorlogse groei",
        "lokaal": "Veendam is een veenkoloniale gemeente in Oost-Groningen met een rijke handelsgeschiedenis. De woningvoorraad bestaat grotendeels uit naoorlogse woningen. Met de aardbevingsproblematiek in de regio wordt verduurzaming steeds vaker gecombineerd met renovatieprojecten.",
        "klimaat": "Groningen heeft de koudste winters van de westelijke provincies. HR++ kozijnen zijn hier extra lonend vanwege het hoge stookverbruik.",
        "label": "Woningen in Veendam hebben gemiddeld energielabel D of E.",
        "markt": "Veendam biedt betaalbare woningen met groot verbeterpotentieel. Verduurzaming verhoogt het energielabel en de woningwaarde direct.",
        "subsidie_lokaal": "Via ISDE, het Nationaal Warmtefonds en mogelijke Groningse regelingen zijn financiering en subsidie goed te combineren.",
    },
    {
        "slug": "hoogezand",
        "stad": "Hoogezand",
        "provincie": "Groningen",
        "wijken": "Sappemeer, Foxhol, Muntendam, Westerbroek en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, portieketagewoningen en veenkoloniale woningen",
        "bouwjaar": "met naoorlogse industriegroei en veenkoloniale lintbebouwing langs kanalen",
        "lokaal": "Hoogezand-Sappemeer maakt deel uit van Midden-Groningen en heeft een gevarieerde woningvoorraad. Wijken in Sappemeer en Hoogezand tellen veel naoorlogse woningen die energetisch sterk verouderd zijn. De combinatie van aardgasafbouw en kozijnenvervanging maakt hier een directe sprong in het energielabel mogelijk.",
        "klimaat": "Midden-Groningen heeft koude winters en een open landschap. Goede isolatie via HR++ kozijnen is hier direct merkbaar op de energierekening.",
        "label": "Naoorlogse woningen in Hoogezand hebben gemiddeld energielabel D of E.",
        "markt": "Hoogezand heeft betaalbare woningen met groot verduurzamingspotentieel. Verduurzaming vergroot de woningwaarde direct.",
        "subsidie_lokaal": "ISDE, Nationaal Warmtefonds en regionale Groningse programma's zijn te combineren voor eigenaar-bewoners in Midden-Groningen.",
    },
    {
        "slug": "winschoten",
        "stad": "Winschoten",
        "provincie": "Groningen",
        "wijken": "Blijham, Scheemda, Reiderland, Winschoten-Noord en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande woningen en historische stadspanden",
        "bouwjaar": "met een rijke handelsgeschiedenis en naoorlogse uitbreidingen in Oldambt",
        "lokaal": "Winschoten is het centrum van de gemeente Oldambt in Oost-Groningen. De stad heeft een gevarieerde woningvoorraad met historische panden en naoorlogse woningen. Door de combinatie van verouderde kozijnen en de transitie van het aardgas is verduurzaming hier urgenter dan gemiddeld.",
        "klimaat": "Oost-Groningen heeft koude, winderige winters. Goed geïsoleerde kozijnen zijn hier extra waardevol voor tochtwering en warmtebehoud.",
        "label": "Woningen in Winschoten hebben gemiddeld energielabel D, E of slechter.",
        "markt": "Oldambt heeft betaalbare woningen. Verduurzaming verhoogt het energielabel en de verkoopwaarde aantoonbaar.",
        "subsidie_lokaal": "Via ISDE, het Nationaal Warmtefonds en Groningse regelingen zijn financiering en subsidie goed beschikbaar voor eigenaar-bewoners in Oldambt.",
    },
    {
        "slug": "heerenveen",
        "stad": "Heerenveen",
        "provincie": "Friesland",
        "wijken": "Skoatterwâld, Akkrum, Tijnje, De Greiden en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, vrijstaande woningen en nieuwbouw in Skoatterwâld",
        "bouwjaar": "met naoorlogse groei en uitgestrekte nieuwbouwwijken als groeistad van Friesland",
        "lokaal": "Heerenveen is een groeigemeente in het hart van Friesland. Naast de moderne uitbreidingen zijn er veel naoorlogse woningen in wijken als De Greiden die energetisch sterk te verbeteren zijn. Kozijnenvervanging is hier een van de meest effectieve verduurzamingsstappen.",
        "klimaat": "Friesland heeft natte, koude winters. De open friese polders verhogen de windbelasting op woningen, waardoor goede kozijnafdichting en HR++ glas extra waardevol zijn.",
        "label": "Naoorlogse woningen in Heerenveen hebben gemiddeld energielabel D of E.",
        "markt": "Heerenveen heeft een actieve woningmarkt als groeigemeente. Verduurzaming verhoogt de waarde en aantrekkelijkheid van je woning direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar. De provincie Friesland heeft aanvullende regelingen voor verduurzaming.",
    },
    {
        "slug": "sneek",
        "stad": "Sneek",
        "provincie": "Friesland",
        "wijken": "Tinga, Pasveer, Sperkhem, IJlst en het Centrum",
        "woningtype": "historische waterstadpanden, naoorlogse rijtjeswoningen en vrijstaande woningen",
        "bouwjaar": "met een rijke watersportgeschiedenis en naoorlogse uitbreidingen",
        "lokaal": "Sneek is de waterstad van Friesland, bekend om het Sneekweek zeilfeest en de friese meren. De woningvoorraad is gevarieerd, van historische grachten-panden tot naoorlogse rijtjeswoningen in wijken als Tinga en Pasveer. Juist de naoorlogse woningbouw heeft sterk te winnen bij nieuwe kozijnen.",
        "klimaat": "Friesland heeft de natste en koudste winters van de westelijke provincies. Goed geïsoleerde kozijnen zijn hier meer dan de moeite waard, de terugverdientijd is door het hoge stookverbruik korter.",
        "label": "Naoorlogse woningen in Sneek scoren gemiddeld energielabel D of E.",
        "markt": "Sneek is populair als waterstad en heeft een actieve woningmarkt. Verduurzaming is een bewuste investering die de woningwaarde vergroot.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar. De provincie Friesland heeft aanvullende subsidiemogelijkheden voor verduurzaming.",
    },
    {
        "slug": "veenendaal",
        "stad": "Veenendaal",
        "provincie": "Utrecht",
        "wijken": "Dragonder, De Batterijen, Schrijverswijk, Kernhem en het Centrum",
        "woningtype": "naoorlogse rijtjeswoningen, twee-onder-een-kapwoningen en Vinex-woningen",
        "bouwjaar": "met sterke naoorlogse groei en continue uitbreidingen als groeigemeente op de Veluwerand",
        "lokaal": "Veenendaal is een van de snelst gegroeide gemeenten van Nederland. De woningvoorraad bestaat overwegend uit gezinswoningen, van naoorlogse rijtjeswoningen tot recente Vinex-woningen. Woningen uit de jaren 70 tot 90 zijn energetisch aan kozijnenvervanging toe.",
        "klimaat": "Op de Veluwerand heeft Veenendaal een continentaal klimaat. HR++ kozijnen zijn hier een directe investering in lagere stookkosten.",
        "label": "Oudere woningen in Veenendaal hebben gemiddeld energielabel C of D.",
        "markt": "Veenendaal heeft een van de actiefste woningmarkten van Midden-Nederland. Verduurzaming verhoogt de woningwaarde direct in deze gespannen markt.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor eigenaar-bewoners in Veenendaal.",
    },
    {
        "slug": "elburg",
        "stad": "Elburg",
        "provincie": "Gelderland",
        "wijken": "Doornspijk, Oostendorp, Oldebroek, 't Harde en het Centrum",
        "woningtype": "historische Hanzepanden, naoorlogse rijtjeswoningen en vrijstaande Veluwse woningen",
        "bouwjaar": "met een uitzonderlijk goed bewaard historisch centrum en naoorlogse uitbreidingen",
        "lokaal": "Elburg is een van de best bewaarde middeleeuwse vestingstadjes van Nederland. Naast het unieke historische centrum zijn er naoorlogse wijken in de gemeente Oldebroek met gezinswoningen die energetisch aan verbetering toe zijn.",
        "klimaat": "Aan het Veluwemeer heeft Elburg een mild klimaat. De naoorlogse woningen profiteren sterk van HR++ kozijnen.",
        "label": "Naoorlogse woningen in de gemeente Oldebroek hebben gemiddeld energielabel C of D.",
        "markt": "Elburg en de Veluwekust zijn populair. Verduurzaming verhoogt de woningwaarde in deze gewilde regio.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in Elburg en de gemeente Oldebroek.",
    },
    {
        "slug": "ermelo",
        "stad": "Ermelo",
        "provincie": "Gelderland",
        "wijken": "Horst, Speuld, Hierden, Ermelo-West en het Centrum",
        "woningtype": "vrijstaande bungalows, Veluwse gezinswoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met een typische Veluwse bebouwing van vrijstaande woningen in bosrijke omgeving",
        "lokaal": "Ermelo is een bosrijke Veluwse gemeente met veel vrijstaande woningen en bungalows. De gemeente is populair bij gezinnen en senioren die rust en natuur zoeken. Kozijnen uit de jaren 70 tot 90 zijn hier energetisch verouderd en aan vervanging toe.",
        "klimaat": "Op de Veluwe zijn de winters relatief droog en koud. Vrijstaande woningen en bungalows met grote glasoppervlakken profiteren extra sterk van HR++ isolatieglas.",
        "label": "Bungalows en vrijstaande woningen in Ermelo hebben door hun glasoppervlak gemiddeld energielabel D.",
        "markt": "Ermelo heeft een gewilde woningmarkt op de Veluwe. Verduurzaming vergroot de aantrekkelijkheid en waarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor woningeigenaren in Ermelo.",
    },
    {
        "slug": "putten",
        "stad": "Putten",
        "provincie": "Gelderland",
        "wijken": "Hulshorst, Nulde, Voorthuizen-deel, Putten-Noord en het Centrum",
        "woningtype": "vrijstaande Veluwse woningen, twee-onder-een-kapwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met een karakteristieke Veluwse woonstructuur en naoorlogse uitbreidingen",
        "lokaal": "Putten is een groene Veluwse gemeente tussen Harderwijk en Barneveld. De woningvoorraad bestaat grotendeels uit vrijstaande woningen en twee-onder-een-kapwoningen op ruime kavels. Na 40 tot 60 jaar zijn kozijnen in veel van deze woningen aan vervanging toe.",
        "klimaat": "Op de Veluwe is het klimaat continentaler en de winters koeler. Goede isolatie via HR++ kozijnen is hier direct merkbaar op de stookkosten.",
        "label": "Oudere woningen in Putten hebben gemiddeld energielabel C of D.",
        "markt": "Putten heeft een solide woningmarkt in een groene omgeving. Verduurzaming is hier een bewuste langetermijninvestering.",
        "subsidie_lokaal": "ISDE en het Nationaal Warmtefonds zijn beschikbaar voor eigenaar-bewoners in Putten.",
    },
    {
        "slug": "hattem",
        "stad": "Hattem",
        "provincie": "Gelderland",
        "wijken": "Hattem-Noord, IJsseldijk, Hattem-Zuid, Wezep en het Centrum",
        "woningtype": "vrijstaande woningen, twee-onder-een-kapwoningen en naoorlogse rijtjeswoningen",
        "bouwjaar": "met een historisch centrum en naoorlogse uitbreidingen langs de IJssel",
        "lokaal": "Hattem is een pittoresk stadje aan de IJssel tussen Zwolle en Harderwijk, bekend om zijn historische rondgang. De gemeente heeft een gevarieerde woningvoorraad van historische panden tot naoorlogse gezinswoningen. Kozijnen uit de jaren 70 en 80 zijn hier energetisch aan vervanging toe.",
        "klimaat": "Aan de IJssel heeft Hattem een gematigd klimaat. Goede isolatie via HR++ kozijnen is direct merkbaar op het stookverbruik en het binnenklimaat.",
        "label": "Oudere woningen in Hattem hebben gemiddeld energielabel C of D.",
        "markt": "Hattem heeft een gewilde woningmarkt door de combinatie van natuur en nabijheid van Zwolle. Verduurzaming vergroot de woningwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor eigenaar-bewoners in Hattem.",
    },
    {
        "slug": "borger",
        "stad": "Borger",
        "provincie": "Drenthe",
        "wijken": "Odoorn, Exloo, Valthe, Nieuw-Buinen en het Centrum",
        "woningtype": "vrijstaande Drentse woningen, naoorlogse rijtjeswoningen en agrarische woningen",
        "bouwjaar": "met een karakteristieke Drentse bebouwing van vrijstaande woningen in een open landschap",
        "lokaal": "Borger-Odoorn is een uitgestrekte Drentse gemeente met het bekende hunebed-centrum. De woningvoorraad bestaat grotendeels uit vrijstaande woningen op ruime kavels in een open Drentse omgeving. Kozijnen uit de jaren 60 tot 85 zijn hier energetisch verouderd.",
        "klimaat": "Het open Drentse landschap heeft een continentaal klimaat met koude winters en windbelasting. Goed geïsoleerde kozijnen zijn hier extra waardevol.",
        "label": "Oudere woningen in Borger-Odoorn hebben gemiddeld energielabel D of E.",
        "markt": "Borger-Odoorn heeft betaalbare woningen in een prachtige Drentse omgeving. Verduurzaming verhoogt het energielabel en de woningwaarde direct.",
        "subsidie_lokaal": "Via ISDE en het Nationaal Warmtefonds zijn alle subsidies beschikbaar voor eigenaar-bewoners in Borger-Odoorn.",
    },
]

# ── Genereer pagina's ────────────────────────────────────────────────────────
output_dir = "C:/Users/knusl/Downloads/kozijnstunter"
generated = []
for s in steden_nieuw:
    filename = "kozijnen-" + s["slug"] + ".html"
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(_make_page(s))
    generated.append(filename)

print("Aangemaakt: " + str(len(generated)) + " paginas")
for fn in generated:
    print("  " + fn)
